### ISSUE TITLE
Finalize API format

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#123]

**Comment by rhodges** [comment]
@pollardld : How do these float your boat?
### Getting Aggregate Data: 
In regards to #118 and #124 
* Use existing logic for **get_results_by_scenario_id**
   * pass: scenario id (int) as **id**
   * pass: export (boolean) as **export** (assumed false)
   * no longer use this to get hydro results
   * OPTION: DO include downstream pourpoint list by default for initial load
### Getting Hydro Data
In regards to (no specific issue?) and #124 
* **get_hydro_results_by_pour_point_id**
   * pass: selected pour point ID (int) as **pourpoint_id**
   * pass: scenario ID (int) as **treatment_id**
   * return: results as decided for #117 
### Getting Downstream Pour Points
As mentioned, this could be folded into **get_results_by_scenario_id**
In regards to #120 
* **get_downstream_pour_points**
   * pass: pour point id (int) as **pourpoint_id**
   * returns: JSON list:
      * geometry: (geojson)
      * name: (string)
      * id: (int)

**Comment by rhodges** [comment]
See 60b36ac5f940d1e32ba5a87ab0c34acd3542f3c7 for details
