### ISSUE TITLE
Structure for ppt flow charts

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#125]
**JSON structure for each object**

```js
{
  pptId: #,
  rx: #,
  timestep: '%Y-%m-%d %H:%M:%S',
  totalFlow: #
}
```

**Example of R output needed:** 
```js
[{
  pptId: 0,
  rx: 1,
  timestep: "2013-01-01 03:00:00",
  totalFlow: 100
},{
  pptId: 0,
  rx: 1,
  timestep: "2013-01-01 06:00:00",
  totalFlow: 200
},{
  pptId: 0,
  rx: 1,
  timestep: "2013-01-01 09:00:00",
  totalFlow: 300
},{
  pptId: 0,
  rx: 1,
  timestep: "2013-01-01 12:00:00",
  totalFlow: 400
},{
  pptId: 1,
  rx: 2,
  timestep: "2013-01-01 03:00:00",
  totalFlow: 200
},{
  pptId: 1,
  rx: 2,
  timestep: "2013-01-01 06:00:00",
  totalFlow: 333
},{
  pptId: 1,
  rx: 2,
  timestep: "2013-01-01 09:00:00",
  totalFlow: 222
},{
  pptId: 1,
  rx: 2,
  timestep: "2013-01-01 12:00:00",
  totalFlow: 444
}]
```

***  

[Billboard Documentation Link](https://naver.github.io/billboard.js/release/latest/doc/Options.html#.data%25E2%2580%25A4rows)  

***  

**Current code. Structure not correct!!!!!!** 

https://github.com/Ecotrust/ucsrb/blob/cd6ecb42eb38a13421da30a08f19517cd1e56993/ucsrb/static/ucsrb/js/app.js#L253-L298

**Comment by rhodges** [comment]
thought I had this ready with b361da12b092c619e46bffd1fddae45810beb51a but this ticket was edited from it's form that I saw in the email:
[{
  pptId: 0,
  rx: null,
  timestep: "2013-01-01 03:00:00",
  totalFlow: null
},{ ... }]
Will chat tomorrow.

**Comment by rhodges** [comment]
PourPoint results are now generated on a point-by-point basis (on click) and do not need to contain all of this info.
