### ISSUE TITLE
Create Rx Form and Model

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ucsrb#216]
* [x] Need input from Mike on how we expect to lead users to a pre-canned Rx (what should the form look like?)
* [x] Evaluate aspects of an Rx and determine if a model is needed, or if these should be hard-coded
   * [x] If model - keep in mind option to generate new "Rx" veg layers in the future and create matching Rx definition via Django Admin

**Insert into the UI workflow**
  * [x] a single-select widget (I lean towards radio-button, but a drop-down would work, too) to the existing form (both .html and .py) 
  
**Attach value to scenario model so that it can be referenced in the model run**
  * [x] update the appropriate treatment scenario model (whichever is used to render reports) to track an integer ID representing the proposed treatment, and
 
**Settings.py lookup**
  * [x] add a lookup to the settings.py file to map that ID to the text description.

**Comment by rhodges** [comment]
Current MVP Plan:
Provide users with a selection between the 5 non-abstract Rx options for now. Associate each with an ID that can be used as Harness input.

**Comment by rhodges** [comment]
So long as it's this simple a model is not needed. Once we build a decision tree, models may offer desired features, or may merely complicate what is a simple selection between 5 options.

**Comment by rhodges** [comment]
the description of the prescriptions can be found in a doc called Snow2Flow Vegetation and Patch Data.pdf and can be found with the layers here: \\KnowSys\GIS\projects\UCSRB_2020\data\PNWRS

**Comment by pollardld** [comment]
Final version uses a char field as opposed to an int
6723e5af15d17184838f72b91a021dafd8310d98
