### ISSUE TITLE
Progress bar strategies for server processes greater than a minute

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#222]
* [ ] Research strategies for watching long term process
* [ ] Choose a design
* [ ] Implement the technique
* [ ] Show user % progress bar
	* 3 runs

**Comment by rhodges** [comment]
This will depend on several soon-to-be created tickets - 
* [ ] a new model will record each treatment's job status
* [ ] Celery or another process scheduler to track overall 'job' status
* [ ] Wrapper utilities to calculate progress of the model and DB import to update the status model instance
