### ISSUE TITLE
Applying Prescriptions to Treatment Scenarios [ 64 hours ]

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ucsrb#250]
* [x] User defines treatment Polygons
  * [x] Auto-apply 'baseline' to all features
  * [x] Zoom to extent
  * [x] Add Rx form to panel
  * [x] select 1+ polygons
  * [x] Applies a treatment to those polygons
  * [x] Unselect all selected polygons
  * [x] Apply unique color to each treatment type [5]
  * [x] Repeat as needed

**Comment by pollardld** [comment]
* [ ] error for users not not needed for May 5th

**Comment by pollardld** [comment]
**MVP**  

* [ ] apply single Rx to all polygons

**Nice to have**

* [ ] apply Rx to individual polygons

**Comment by pollardld** [comment]
* [ ] Update illustrator with changed workflow 
* [ ] Add `required` attribute to required input fields in forms.py
* [ ] No stream layers for the 5th

**Comment by pollardld** [comment]
* [ ] Return Geojson with attributes attached
* [ ] Apply all button
