### ISSUE TITLE
branch "iss227": Celery/Rabbit [CRITICAL/MainProcess] Couldn't ack 1, reason:ConnectionResetError(104, 'Connection reset by peer')

### ISSUE THREAD

**Issue by rhodges** [Ecotrust/ucsrb#261]
Following similar comments here: https://github.com/celery/celery/issues/4867 

Noticed this: https://github.com/celery/celery/issues/4867#issuecomment-857439400

in /etc/conf.d/celery I had CELERYD_OPTS="... --concurrency=0 ..."

Changing to concurrency=1...

**Comment by rhodges** [comment]
Other Ideas:
* [ ] DEBUG=False
* [ ] Restart RabbitMQ

**Comment by rhodges** [comment]
Seeing error in RabbitMQ logs:
`2021-07-20 22:16:09.910 [error] <0.2088.0> closing AMQP connection <0.2088.0> (127.0.0.1:57810 -> 127.0.0.1:5672):
missed heartbeats from client, timeout: 60s`
Other research: 
* http://www.freekb.net/Article?id=3019
   * set higher heartbeat in main RabbitMQ config
* https://github.com/celery/celery/issues/4980
   * Downgrade from celery v4.4.7 to v4.1.1
      *  Flower 0.9.7 doesn't like this
* Nuke option: use Redis instead of RabbitMQ

**Comment by rhodges** [comment]
* Higher heartbeat in /etc/rabbitmq/rabbitmq.conf:
   * did not do anything
* Downgrade celery to v4.1.1
   * No effect....

**Comment by rhodges** [comment]
Swapping RabbitMQ for Redis did the trick.

**Comment by rhodges** [comment]
Fixed: 0e5a2b1a686dfc795f54bd264d89d549b7805e13

**Comment by noelmcloughlin** [comment]
Found this searching.  I had same issue with celery/rabbitmq cluster where two airflow taskgroups were constrained to concurrency=1 (added for troubleshooting another issue), so I just removed concurrency=1 parameter completely.
