### ISSUE TITLE
Reporting UI

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#27]
* [ ] Redesign template to report list of values for Forest Management report - no need for guessing at format
* [ ] Hydro results need to be line graph, not bar graph
* [ ] Hydro results need to fit inside panel (overflow if too large - test with short screen)

**Comment by rhodges** [comment]
* [ ] Redesign template to report list of values for Forest Management report - no need for guessing at format
* [ ] Hydro results need to be line graph, not bar graph
* [ ] Hydro results need to fit inside panel (overflow if too large - test with short screen)

**Comment by pollardld** [comment]
#115
