### ISSUE TITLE
Create home page template

### ISSUE THREAD

**Issue by pollardld** [Ecotrust/ucsrb#3]
home page template is one of two templates needed  

<img width="586" alt="screen shot 2017-10-06 at 4 18 04 pm" src="https://user-images.githubusercontent.com/2632164/31301847-fb8565c4-aab1-11e7-8728-5b9c31d0d9bb.png">

**Comment by rhodges** [comment]
Here's the file location: https://github.com/Ecotrust/ucsrb/blob/master/ucsrb/templates/index.html
